theme: minima
title: "Home"
baseurl: "/simys-blog" # This is crucial for correct path resolution
url: "https://simrenbasra.github.io" # Base URL of your GitHub Pages site

header_pages:
  - about_me.md
  - my_projects.md



